CALLSIGN = "OS42-Groundstation (VE3SVF)"
LAT = 43.5904578
LONG = -79.513569
ALT = 150
RADIO = "RTL-SDR + Custom Software"
ANTENNA = "7 el Yagi"
ENABLE_DEV = False #Do not touch for regular flights! Only for testing the SondeHub connetion!
LAT_OFFSET = 0 #Do not change! Make sure this is zero!
LONG_OFFSET = 0 #Do not change! Make sure this is zero!
ALT_OFFSET = 0 #Do not change! Make sure this is zero!
